### ISSUE TITLE
Bugs and Feature

### ISSUE THREAD

**Issue by zaidansari42** [Asma-Abed/tesla-clone#1]
Bug- Here there is a slight gap on the bottom while opening the sidebar menu, the white BG should cover the whole area till bottom. The Gap is visible also on the mobile and Tab Version. Please resolve it.

These Features are the common small features you must have, which all of the websites already have that are in porduction
1. On clicking the left (blurred / overlay) section, this Side menu should close.
2. On clicking the Tesla logo on the homepage, It should load the top of the Tesla page / Landing Page.

**Comment by Asma-Abed** [comment]
> Bug- Here there is a slight gap on the bottom while opening the sidebar menu, the white BG should cover the whole area till bottom. The Gap is visible also on the mobile and Tab Version. Please resolve it.
> 
> These Features are the common small features you must have, which all of the websites already have that are in porduction
> 
>     1. On clicking the left (blurred / overlay) section, this Side menu should close.
> 
>     2. On clicking the Tesla logo on the homepage, It should load the top of the Tesla page / Landing Page.

Thank you Zaid for going through my clone, I appreciate it.
You're right, I noticed these issues before, but couldn't have the time to tackle them.
I'll try to go back to this project when I can.
